### ISSUE TITLE
Strings missing localization in ASR node

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#109]
Some strings seem to be missing a German localization in the node properties window of ASR nodes:
- Tab title "RecognitionTab"
- Button label "TryRecognition" (note that the T is underlined on Windows, should probably be a hotkey)
- List title "InputWords"

Do we also want to localize "DirectGrammar" and such?

![screenshot](https://user-images.githubusercontent.com/8291392/48658797-0b202100-ea48-11e8-8a60-c0a3fbfde1ed.png)

**Comment by alexanderkoller** [comment]
@timobaumann I have added the missing localizations. They are in Diamant/src/main/resources/com.clt.diamant.DiaMant.properties, at the end of the file.

Could I ask you to double-check that both the English and the German localizations (both on the "Speech Recognition" tab and the "Options" tab) are correct terminology?

**Comment by timobaumann** [comment]
@alexanderkoller : I'd prefer 
`DirectGrammar=<Generate from alternatives>` (<Aus Alternativen generieren>)
instead of <Generate from keywords>. keywords implies that you can say other stuff as well (you can't) and doesn't imply that you can have arbitrarily complex rules in there (you can -- or at least should be able to).

I'm not sure about recognize in background. When I check it, the recognition ends immediately. I don't know if further recognition results are integrated later, though. (A theoretical use-case could be to listen for ASR while saying something via TTS; obviously, in that case the flow can't depend on what branch is taken. It could work together with writing the result to a variable, though, which would only be filled once the recognition completes. I don't know whether/how this is integrated, though.) Can you open a bug on that?

**Comment by alexanderkoller** [comment]
Ad "generate from alternatives": I'd like to use the same word in `<Generate from X>` as in the title of the keyword list right below the dropdown for the languages. The latter used to be called "input words", which I found unclear.

I'm not married to calling them "keywords". I don't quite understand what you don't like about "keywords" and why you find "alternatives" better - could you elaborate? (To me, "alternatives" seems too vague - many things can be "alternatives". Also, if "enable garbage" is on, you _can_ say things that are not the keywords and the keywords will still be recognized - at least if the documentation is correct, I haven't tried it.)

Ad "recognize in background": Will do.

**Comment by alexanderkoller** [comment]
-> #119

**Comment by alexanderkoller** [comment]
I'm struggling with the negation in "Keywords doesn't imply that you can have arbitrarily complex rules in there". If I understand you correctly, this presupposes that DirectGrammars can have arbitrary patterns in the "keywords" list. As far as I can tell, they can't; see our discussion on #110 .

**Comment by timobaumann** [comment]
re: arbitrarily complex rules: rules, not regexps. specifications that the grammar can generate from, i.e. things with parentheses, kleene stars, alternative pipes. no non-terminals.

**Comment by timobaumann** [comment]
re: keywords/alternatives/whatnot
the code that is concerned here is https://github.com/dialogos-project/dialogos/blob/master/Diamant/src/main/java/com/clt/diamant/graph/nodes/AbstractInputNode.java#L1000 and following lines. 
In essence, we're taking the content of the "keyword/input words" lines and joining them with "|" pipe symbols that indicate alternatives in the grammar.  
Each "keyword/input words" line can contain anything you want, as long as we end up with a grammar in the end. That's why I find keywords too limiting. 

Garbage is handled further downstream: when exporting the grammar to JSGF, we insert a garbage rule (that expands to any sequence of phones) between all terminals in the grammar. This also works for grammars from expressions or grammars that you have defined yourself.

**Comment by alexanderkoller** [comment]
Oh, interesting. So basically a DirectGrammar "alternative" can be anything that can be on the right-hand side of a grammar, except without nonterminals?

I just tried this with patterns like "(yes)+" and such, and Sphinx only recognized a single "yes" every time. Can you show me an example dialog where this actually works as intended?

**Comment by timobaumann** [comment]
it seems like + doesn't work. It works with yes yes*

**Comment by timobaumann** [comment]
if JSGF supports +, then this is a Sphinx bug and we should report it. if JSGF doesn't support it, we'll have to fix our export from the DialogOS grammar to JSGF.
