### ISSUE TITLE
DialogOS crashes all the time

### ISSUE THREAD

**Issue by TheresaSchmidt** [dialogos-project/dialogos#138]
We haven't found out yet whether there is any regularity but DialogOS crashes very often. Many times, this happens when running the dialogue, especially at speech recognition nodes. But sometimes it just stops working at any time during design or execution.
Sorry for not being very specific, but I thought I should mention it here...

**Comment by timobaumann** [comment]
Hi Theresa, 
it would help tremendously if you could execute DialogOS from the commandline rather than by double-clicking its icon. That way, any messages that it outputs before/while dying while appear on the commandline and you could paste them to the bug report. Without such messages, it is virtually impossible to trace the problem. thanks.

**Comment by alexanderkoller** [comment]
I spoke to @TheresaSchmidt offline and asked her to send us minimal reproducible bugs.
