### ISSUE TITLE
Step into subgraphs in debugger

### ISSUE THREAD

**Issue by TheresaSchmidt** [dialogos-project/dialogos#148]
When running the debugger, there is a possibility to show the subgraph by clicking "StepInto". However, the button is only active right before the subgraph is executed. It would be nice if you could make the subgraph able to be stepped into during its whole execution.

**Comment by alexanderkoller** [comment]
Hi, thank you for the issue.

I'm not sure I understand what you would like to happen. What would it mean to "step into" a subgraph while it is being executed? At that point, aren't we already "inside" the subgraph?

**Comment by TheresaSchmidt** [comment]
The program is inside it but we if we don't use "StepInto" the actual nodes are not visible. Instead the subgraph node is shown as active node for the whole execution time of the subgraph.

![grafik](https://user-images.githubusercontent.com/36304889/50979677-4c3c2b00-14f7-11e9-8680-4316786f4931.png)
![grafik](https://user-images.githubusercontent.com/36304889/50979730-6544dc00-14f7-11e9-90db-4b846766a56f.png)

**Comment by alexanderkoller** [comment]
So if I understand you correctly, the behavior that you don't like is that if you e.g. click on "Step Over" to step over the subgraph node, the following happens:

- Subgraph node is executed.
- During execution of the subgraph node, DialogOS always displays the outer graph (which contains the subgraph node), not the contents of the subgraph.
- During execution of the subgraph node, the active node is always the subgraph node.

Instead, you would like the following thing to happen:

- During execution of the subgraph node, the contents of the subgraph are displayed, and each individual node inside the subgraph becomes active when it is executed.

Is this what you mean?

What happens when you just "Run" the dialog instead of "Debug"ging it? Does it make the nodes inside the subgraph active, or just the subgraph node itself?

**Comment by TheresaSchmidt** [comment]
Also, @marcalt94 mentioned, that it is possible to use "StepInto" to get from the main graph to one of its subgraphs but that it doesn't work recursively for subgraphs of subgraphs.

**Comment by TheresaSchmidt** [comment]
Concerning my issue: after I have used it several times I have noticed now that sometimes what I want actually works. However, I haven't found a regularity, yet...

**Comment by TheresaSchmidt** [comment]
The `Pause` button does just what I need.
