### ISSUE TITLE
dialogos.app needs www. to work

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#85]
dialogos.app doesn't do anything, www.dialogos.app works.
is that fixable?

**Comment by alexanderkoller** [comment]
dialogos.app works for me (Mac, Chrome). Can you give me details of your setup and/or try with another browser?

**Comment by timobaumann** [comment]
that's firefox 61 on ubuntu 18.04. 
It appears that it works in w3m so I'm wondering if that's a problem on my end. 
@akoehn , does dialogos.app work for you (assuming you have a linux+firefox setup to test with)?

**Comment by akoehn** [comment]
Doesn't work on FF mobile as well.  Had problems with that before already.

**Comment by akoehn** [comment]
Same on Chrome 67 and FF 61 here.  The problem seems to be that http://dialogos.app works as expected, but htttpS://dialogos.app does not.

HTTP works:
```
telnet dialogos.app 80
Trying 184.168.131.241...
Connected to dialogos.app.
Escape character is '^]'.
GET / HTTP/1.1
HOST: dialogos.app

HTTP/1.1 301 Moved Permanently
Server: nginx/1.12.2
Date: Sat, 28 Jul 2018 04:56:31 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Location: https://www.dialogos.app
```

httpS does not:
```
openssl s_client -connect dialogos.app:443
[just hangs without result]
```

Since https is available, the browsers will try to establish a secure connection and then fail. w3m doesn't doe that and therefore works.

**Comment by timobaumann** [comment]
```
1. dialogos.app
2. www.dialogos.app
3. http://dialogos.app
4. http://www.dialogos.app
5. https://dialogos.app
6. https://www.dialogos.app
```
works: 2 4 6
doesn't work for timo: 1 3 5

**Comment by alexanderkoller** [comment]
Github Pages only support a single domain (i.e. either dialogos.app or www.dialogos.app, but not both): https://stackoverflow.com/questions/16454088/can-github-pages-cname-file-contain-more-than-one-domain

The solution seems to be domain forwarding. I have configured our domain provider to forward dialogos.app to https://www.dialogos.app.

Unfortunately, it seems that domain forwarding + HTTPS is tricky: https://ph.godaddy.com/community/Managing-Domains/Forwarding-from-HTTPS/td-p/55176

We can look into this more, but right now it is not quite clear how this problem can be solved to our complete satisfaction.

**Comment by alexanderkoller** [comment]
If we're willing to live without https, domain forwarding may be easier. Thoughts?

**Comment by timobaumann** [comment]
I'm willing to take the risk of a man-in-the-middle attack.

**Comment by timobaumann** [comment]
@alexanderkoller : can you attempt the fix that would disable https?

**Comment by alexanderkoller** [comment]
I'll try. It seems tricky; Github really seems to want to use https.

This should not block the release, though, right?

**Comment by alexanderkoller** [comment]
Okay. Here are some additional findings:

- Regardless of whether or not "Enforce HTTPS" is checked on https://github.com/dialogos-project/dialogos-project.github.io/settings, Github tries to serve the site as HTTPS.

- `[Configuring Github to respond to dialogos.app](https://help.github.com/articles/setting-up-an-apex-domain/)` directly - by directing dialogos.app to a Github IP adress - does not work (Chrome shows a huge error message about an invalid HTTPS certificate).

- This is probably because [Github pages can only be served under www.dialogos.app or dialogos.app, but not both](https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/td-p/7116).

- The accepted solution seems to be to use Cloudflare as the DNS for dialogos.app and then [create Cloudflare rules](https://www.linuxguideandhints.com/fedora/git.html#setting-up-cloudflare-and-github-pages) for redirecting one URL to the other.

I don't have the time right now to fight my way through this jungle. If one of you has time, I'd be happy to give you the access details to my GoDaddy account (where we bought the domain dialogos.app) and you can see if you can make it work. Otherwise, let's live without httpX://dialogos.app for now. (Btw the URL in the paper is with www, so works as advertised.)

**Comment by timobaumann** [comment]
appears to be fixed.
